---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: empms-employee
  name: empms-employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-employee
  template:
    metadata:
      labels:
        app: empms-employee
    spec:
      containers:
      - image: 276391883698.dkr.ecr.us-east-1.amazonaws.com/ot-ms:employee
        imagePullPolicy: Always
        name: empms-employee
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: empms-employee
spec:
  type: ClusterIP
  selector:
    app: empms-employee
  ports:
  - protocol: TCP
    port: 8083
