---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: empms-frontend
  name: empms-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: empms-frontend
    spec:
      containers:
      - image: 276391883698.dkr.ecr.us-east-1.amazonaws.com/ot-ms:frontend
        imagePullPolicy: Always
        name: empms-frontend
        ports:
        - containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: empms-frontend
spec:
  type: ClusterIP
  selector:
    app: empms-frontend
  ports:
  - protocol: TCP
    port: 3000
