REGISTRY=276391883698.dkr.ecr.us-east-1.amazonaws.com/ot-ms
DB_tag=${REGISTRY}:db
Gateway_tag=${REGISTRY}:gateway
Attendance_tag=${REGISTRY}:attendance
Frontend_tag=${REGISTRY}:frontend
Webserver_tag=${REGISTRY}:webserver
ElasticSearch_tag=${REGISTRY}:es
Employee_tag=${REGISTRY}:employee
Salary_tag=${REGISTRY}:salary
IMAGES=($DB_tag $Gateway_tag $Attendance_tag $Frontend_tag $Webserver_tag $ElasticSearch_tag $Employee_tag $Salary_tag)
MAX_ALLOWED_IMAGE_SIZE=9000000000 #(size is in bytes)
