---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: empms-attendance
  name: empms-attendance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-attendance
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: empms-attendance
    spec:
      containers:
      - image: 276391883698.dkr.ecr.us-east-1.amazonaws.com/ot-ms:attendance
        imagePullPolicy: Always
        name: empms-attendance
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /hello
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /hello
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /hello
            port: 8081
          failureThreshold: 30
          periodSeconds: 10       
---
apiVersion: v1
kind: Service
metadata:
  name: empms-attendance
spec:
  type: ClusterIP
  selector:
    app: empms-attendance
  ports:
  - protocol: TCP
    port: 8081
