apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: empms-es
  name: empms-es
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: empms-es
  template:
    metadata:
      labels:
        app: empms-es
    spec:
      containers:
      - image: 276391883698.dkr.ecr.us-east-1.amazonaws.com/ot-ms:es
        imagePullPolicy: Always
        name: empms-es
        ports:
        - containerPort: 9200
        livenessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: empms-es
spec:
  type: ClusterIP
  selector:
    app: empms-es
  ports:
  - protocol: TCP
    port: 9200
