---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empms-webserver
  labels:
    app: empms-webserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: empms-webserver
  template:
    metadata:
      labels:
        app: empms-webserver
    spec:
      containers:
      - name: empms-webserver
        image: 276391883698.dkr.ecr.us-east-1.amazonaws.com/ot-ms:webserver
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: empms-webserver
spec:
  selector:
    app: empms-webserver
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
