---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empms-webserver
  labels:
    app: empms-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-webserver
  template:
    metadata:
      labels:
        app: empms-webserver
    spec:
      containers:
      - name: empms-webserver
        image: opstree/empms-webserver:1.0
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: empms-webserver
spec:
  selector:
    app: empms-webserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30444
