---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: empms-salary
  name: empms-salary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-salary
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: empms-salary
    spec:
      containers:
      - image: 276391883698.dkr.ecr.us-east-1.amazonaws.com/ot-ms:salary
        imagePullPolicy: Always
        name: empms-salary
        ports:
        - containerPort: 8082
---        
apiVersion: v1
kind: Service
metadata:
  name: empms-salary
spec:
  type: ClusterIP
  selector:
    app: empms-db
  ports:
  - protocol: TCP
    port: 8082
